---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --explicit_end, --explicit_start]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --explicit_end, --explicit_start]

  - repo: local
    hooks:
      - id: packer-fmt
        name: Packer fmt
        description: Format Packer files with packer fmt
        entry: packer fmt -diff
        language: system
        files: \.pkr\.(hcl|json)$
        pass_filenames: true
      - id: packer-validate
        name: Packer validate
        description: Validate Packer files with packer validate
        entry: packer validate
        language: system
        files: \.pkr\.(hcl|json)$
        pass_filenames: true
...
